### ISSUE TITLE
needs update for string.data changes

### ISSUE THREAD

**Issue by stevengj** [nalimilan/StringEncodings.jl#12]
After JuliaLang/julia#19449, soon to be merged for Julia 0.6, you will no longer be able to access the raw bytes of a string via `string.data`; instead, do `Vector{UInt8}(string)`.  For example, this affects:

https://github.com/nalimilan/StringEncodings.jl/blob/e6fd1bfa601a66207afc3061c479678548dd227f/deps/build.jl#L21

**Comment by nalimilan** [comment]
Thanks for the notice. See https://github.com/nalimilan/StringEncodings.jl/pull/13.
