### ISSUE TITLE
StringEncodings.jl uses libiconv-1.14 which is broken on Ubuntu 17.04 64-bit

### ISSUE THREAD

**Issue by sambitdash** [nalimilan/StringEncodings.jl#16]
``
~/.julia/v0.6/StringEncodings/deps/src/libiconv-1.14$ uname -a
Linux  4.10.0-30-generic #34-Ubuntu SMP Mon Jul 31 19:38:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
``
Independently, building libiconv-1.14 also reports the exact same error. 

``
make[3]: Leaving directory '/home/sambit/.julia/v0.6/StringEncodings/deps/src/libiconv-1.14'
gcc -DHAVE_CONFIG_H -DEXEEXT=\"\" -I. -I.. -I../lib  -I../intl -DDEPENDS_ON_LIBICONV=1 -DDEPENDS_ON_LIBINTL=1   -g -O2 -c progname.c
In file included from progname.c:26:0:
./stdio.h:1010:1: error: ‘gets’ undeclared here (not in a function)
 _GL_WARN_ON_USE (gets, "gets is a security hole - use fgets instead");
 ^
Makefile:914: recipe for target 'progname.o' failed
make[2]: *** [progname.o] Error 1
``

libiconv-1.15 does not have these errors and builds properly.

**Comment by nalimilan** [comment]
Thanks for the PR, but you shouldn't have to build libiconv at all on Ubuntu: the needed functions should be provided by libc. Isn't that the case?

**Comment by sambitdash** [comment]
Yes. But the build.jl may need changes so that it does not download the
libiconv in case the functionality exists. Seems the current provides
directive is not honored as in Linux the debian package manager does not
show libiconv as a registered package (it's subsumed into glibc). So one
may need to check for a linking symbol like a library version or iconv
function call.

The second reason I didn't pursue was if there was a desired intent to keep
the iconv capability with a locally linked package so that when deployed it
does not interfere with the system interface.

If you prefer option 1, I will try to modify the build.jl if that can take
a linking symbol as part of directives.

Regards,

Sambit


On Aug 9, 2017 1:52 AM, "Milan Bouchet-Valat" <notifications@github.com>
wrote:

Thanks for the PR, but you shouldn't have to build libiconv at all on
Ubuntu: the needed functions should be provided by libc. Isn't that the
case?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/nalimilan/StringEncodings.jl/issues/16#issuecomment-321070632>,
or mute the thread

**Comment by sambitdash** [comment]
Moreover, libiconv should not be linked to as it's GPL and Julia packages
are MIT. glibc may be the only option.

https://en.m.wikipedia.org/wiki/Iconv.

Regards,

Sambit

**Comment by sambitdash** [comment]
PR# 17 merged hence closing and opening a new issue to track package to depend on the glibc version of iconv.

**Comment by nalimilan** [comment]
> Moreover, libiconv should not be linked to as it's GPL and Julia packages are MIT. glibc may be the only option. https://en.m.wikipedia.org/wiki/Iconv.

Julia packages can be any license they want. StringEncodings is MIT, but it could be GPL if I wanted to. The license remains MIT as long as we don't install GNU libiconv, which is the case for most platforms (or should be). Building the glibc would be much heavier, and would probably conflict with the system's libc.
