### ISSUE TITLE
New release needed post 0.2.2. 

### ISSUE THREAD

**Issue by sambitdash** [nalimilan/StringEncodings.jl#20]
The 0.2.2 is downloading libiconv-1.15. However, the fix in the build.jl needs to hit the metadata so that the iconv is picked up from the libc.

**Comment by nalimilan** [comment]
See https://github.com/JuliaLang/METADATA.jl/pull/10892.

**Comment by sambitdash** [comment]
Thanks. Appreciate your help and support.
